version: '3.8'

services:
  # Solo la base de datos PostgreSQL con PostGIS para desarrollo
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: routes_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: routes_db
      POSTGRES_USER: routes_user
      POSTGRES_PASSWORD: routes_password
    ports:
      - '5433:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - routes_dev_network

  # Adminer para administrar la base de datos
  adminer:
    image: adminer:latest
    container_name: routes_adminer_dev
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - routes_dev_network

volumes:
  postgres_dev_data:

networks:
  routes_dev_network:
    external: true
    name: routes_shared_network
